"""Asthma health recommendation tools - agent-driven analysis."""

from __future__ import annotations

from typing import Any
from datetime import datetime


def generate_asthma_health_recommendation_tool(
    aqi_value: float,
    aqi_category: str,
    prediction_context: dict[str, Any],
    risk_level: str,
    outdoor_activity: str,
    exercise_recommendation: str,
    medication_reminder: bool,
    mask_recommendation: bool,
    indoor_air_quality_tips: list[str],
    symptoms_to_watch: list[str],
    emergency_advice: str,
    security_context: dict[str, Any] | None = None
) -> dict[str, Any]:
    """
    Format and structure asthma health recommendations generated by the agent.
    
    This tool is called by the agent after it has analyzed the AQI data and determined
    the appropriate health recommendations. The agent's LLM makes all severity and
    recommendation decisions.
    
    Args:
        aqi_value: Current or predicted AQI value
        aqi_category: AQI category from prediction
        prediction_context: Additional context from prediction (fire count, wind speed, etc.)
        risk_level: Risk level determined by agent ("Low", "Moderate", "High", "Severe")
        outdoor_activity: Agent's recommendation ("Safe", "Limited", "Avoid")
        exercise_recommendation: Agent's exercise guidance ("Normal", "Reduce", "Avoid")
        medication_reminder: Whether medication should be taken (agent's decision)
        mask_recommendation: Whether N95 mask should be worn (agent's decision)
        indoor_air_quality_tips: List of tips generated by agent
        symptoms_to_watch: List of symptoms to monitor (agent's assessment)
        emergency_advice: Emergency guidance from agent
        security_context: CrewAI security context (unused, for compatibility)
        
    Returns:
        Dict containing structured health recommendations
    """
    print(f"[DEBUG {datetime.now().isoformat()}] generate_asthma_health_recommendation_tool invoked")
    print(f"[DEBUG] Agent determined risk_level: {risk_level} for AQI: {aqi_value}")
    
    return {
        "risk_level": risk_level,
        "outdoor_activity": outdoor_activity,
        "exercise_recommendation": exercise_recommendation,
        "medication_reminder": medication_reminder,
        "mask_recommendation": mask_recommendation,
        "indoor_air_quality_tips": indoor_air_quality_tips,
        "symptoms_to_watch": symptoms_to_watch,
        "emergency_advice": emergency_advice,
        "aqi_value": aqi_value,
        "aqi_category": aqi_category
    }

