"""Configuration module for InterState-AccountabilityAgent."""

from .border_stations import DELHI_BORDER_STATIONS, get_border_station, is_border_station
from .thresholds import (
    SURGE_AQI_THRESHOLD,
    FIRE_CORRELATION_RADIUS_KM,
    HIGH_CONTRIBUTION_FIRE_COUNT,
    MIN_CONFIDENCE_SCORE,
    NASA_DATA_MISSING_PENALTY,
    DSS_DATA_MISSING_PENALTY,
    LOW_FIRE_COUNT_PENALTY,
    HIGH_DISTANCE_PENALTY,
    CORRELATION_WINDOW_HOURS,
    MAX_DATA_AGE_HOURS,
    EXECUTION_TIMEOUT_MINUTES,
    S3_READ_RETRIES,
    CAQM_SUBMISSION_RETRIES,
    RETRY_BACKOFF_BASE_SECONDS,
)

__all__ = [
    "DELHI_BORDER_STATIONS",
    "get_border_station",
    "is_border_station",
    "SURGE_AQI_THRESHOLD",
    "FIRE_CORRELATION_RADIUS_KM",
    "HIGH_CONTRIBUTION_FIRE_COUNT",
    "MIN_CONFIDENCE_SCORE",
    "NASA_DATA_MISSING_PENALTY",
    "DSS_DATA_MISSING_PENALTY",
    "LOW_FIRE_COUNT_PENALTY",
    "HIGH_DISTANCE_PENALTY",
    "CORRELATION_WINDOW_HOURS",
    "MAX_DATA_AGE_HOURS",
    "EXECUTION_TIMEOUT_MINUTES",
    "S3_READ_RETRIES",
    "CAQM_SUBMISSION_RETRIES",
    "RETRY_BACKOFF_BASE_SECONDS",
]
